      SUBROUTINE BCON(AK,IBC,N,F,IWRIT,IWR)
C     APPLIES BOUNDARY CONDITIONS TO MATRIX AK AS WELL AS
C     ALTERING 'LOAD VECTOR', F FOR PRESCRIBED DISPLACEMENTS.
C     BY SETTING DIAG = 1. AND ROW AND COL TO ZERO IN REST.
C     USES COUNTER IBC WHICH IS 0 IF FREE, 1 IF REST. TO ZERO,
C     -1 IF REST. TO NON-ZERO VALUE
C     ON ENTRY F HAS LOADS FOR FREE ARIABLES AND DISPLACEMENTS FOR
C     REST. (POSSIBLY ZERO) VARIABLES
C     ON EXIT THE LATTER ARE UNCHANGED BUT LOADS ARE ALTERED
C
      DOUBLE PRECISION AK(N,N),F(N)
      INTEGER N,IBC(N),I,J,IPRS,IWRIT,IWR
C
      IPRS = 0
      DO 10 I=1,N
      II = IBC(I)
      IF (II.LT.0) IPRS = 1
      IF (II.NE.0) AK(I,I) = 1.D0
      IF (I.EQ.N) GO TO 10
        DO 20 J=1+1,N
        JJ = IBC(J)
        IF (II.EQ.0.AND.JJ.EQ.0) GO TO 20
C     ABOVE BOTH FREE, BELOW BOTH REST
        IF (II.NE.0.AND.JJ.EQ.0) GO TO 25
C     BELOW I REST OR PRESC
        IF (II.NE.0) THEN
          F(J) = F(J) - AK(I,J)*F(I)
C     BELOW J REST OR PRESC
        ELSE
          F(I) = F(I) - AK(I,J)*F(J)
        ENDIF
   25   AK(I,J) = 0.d0
   20   CONTINUE
   10 CONTINUE
C
      IF (IWRIT.NE.0) THEN
        WRITE (IWR,1000)
 1000   FORMAT(/,1X,'STIFF.MAT.AFTER B.CONDS.IS'/)
        DO 30 I=1,N
          WRITE(IWR,67) (AK(I,J),J=1,N)
   30   CONTINUE
        IF (IPRS.EQ.1) WRITE(IWR,1001) F
 1001   FORMAT(/,1X,'MODIFIED LOAD VECTOR AFTER B CONDS IS',
     1          1X,5G13.4,/)
   67   FORMAT(1X,7G12.5)
      ENDIF
C
      RETURN
      END