      SUBROUTINE FORCE(AN,ANIT,E,ARA,AL,X,Z,P,IWRIT,IWR,
     1                 ITUM,ADUM1,ADUM2,ADUM3)
C     ARGUMENTS IN LINE ABOVE AND ARRAY X NOT USED FOR SHALLOW TRUSS
C
C     COMPUTES INTERNAL.FORCE IN A SHALLOW TRUSS ELEMENT
C     USING (2.7) AND (2.8)
      DOUBLE PRECISION Z(2),P(4),X(2),AN,ANIT,E,ARA,AL,ADUM1,ADUM2,
     1                 ADUM3,EA,EAL,U21,W21,Z21
      INTEGER IWRIT,IWR

C
      EA = E*ARA
      EAL = EA/AL
      U21 = P(2) - P(1)
      W21 = P(4) - P(3)
      Z21 = Z(2) - Z(1)
      AN = U21 + (Z21*W21/AL) + 0.5D0*(W21*W21*AL)
      AN = EAL*AN + ANIT
      IF (IWRIT.NE.0) WRITE (IWR,1000) AN
 1000 FORMAT(/,1X,'AXIAL FORCE AN= ',G13.5/)
      RETURN
      END