      SUBROUTINE INPUT(E,ARA,AL,QFI,X,Z,ANIT,IBC,IRE,IWR,AK14S,ID14S,
     1                NDSP,NV,AK15,
     2                ADUM1,IDUM)
C     ARGUMENTS IN LINE ABOVE AND ARRAY X NOT USED FOR SHALLOW TRUSS
C
C     READS INPUT FOR TRUSS ELEMENT
C
      DOUBLE PRECISION E,ARA,AL,QFI(NV),X(2),Z(2),ANIT,AK14S(4),AK15,
     1                 ADUM1
      INTEGER NV,IDUM,i,NDSP,ID14S(4),IBC(NV)
C
      READ(IRE,*) NV,EA,AL,ANIT
      E = EA
      ARA = 1.D0
      WRITE(IWR,1000) NV,EA,AL,ANIT
 1000 FORMAT(/,1X,'NV=NO. OF VARBLS.=',G13.5,/,1X,
     1      'EA=',G13.5,/,1X,
     2      'AL=EL.LENGTH=',G13.5,1X,
     3      'ANIT=INIT.FORCE=',G13.5,/)
      IF (NV.NE.4.AND.NV.NE.5) STOP 'INPUT 1000'
      READ(IRE,*) Z(1),Z(2)
      WRITE(IWR,1001) Z(1),Z(2)
 1001 FORMAT(/,1X,'Z CO-ORD OF NODE 1=',G13.5,1X,
     1      'Z CO-ORD OF NODE 2=',G13.5,/)
      READ(IRE,*) (QFI(I),I=1,NV)
      WRITE(IWR,1002) (QFI(I),I=1,NV)
 1002 FORMAT(/,1X,'FIXED LOAD OR DISP.VECTOR, QFI=',/,1X,5G13.5,/)
      WRITE(IWR,1008)
 1008 FORMAT(/,1X,'IF IBC(I)-SEE BELOW-=0, VARIABLE=A LOAD',/,1X,
     2      'IF IBC(I)-SEE BELOW-=-1, VARIABLE=A DISP.',/)
      READ(IRE,*) (IBC(I),I=1,NV)
      WRITE(IWR,1003) (IBC(I),I=1,NV)
 1003 FORMAT(/,1X,'BOUND.COND.COUNTER, IBC',/,1X,
     1      '=0, FREE:=1, REST.TO ZERO:=-1 REST.TO NON-ZERO',/,
     2      1X,5G13.5,/)
      READ(IRE,*) NDSP
      IF (NDSP.NE.0) THEN
        READ(IRE,*) (ID14S(I),I=1,NDSP)
        READ(IRE,*) (AK14S(I),I=1,NDSP)
        DO 40 I=1,NDSP
          WRITE(IWR,1004) AK14S(I), ID14S(I)
 1004     FORMAT(/,1X,'LINEAR SPRING OF STIFFNESS',G13.5,/,1X,
     1          'ADDED AT VAR.NO.',G13.5,/)
   40   CONTINUE
      ENDIF
C
      IF (NV.EQ.5) THEN
        READ(IRE,*) AK15
        WRITE(IWR,1005) AK15
 1005   FORMAT(/,1X,'LINEAR SPRING BETWEEN VARBLS. 1 AND 5 OF STIFF ',
     1        G13.5,/)
      ENDIF
C
      RETURN
      END